### PR TITLE
Adjust resolve-url-loader to work with sass-loader 4.0

### LINKED ISSUE #22: incompatible with sass-loader 3.2.2
As sass-loader fix something about it's sourcemap, resolve-url-loader can not find the correct resource and crash.

### PR DESCRIPTION
**Pull request by cevou**
This fixes #22. After the change in https://github.com/jtangelder/sass-loader/pull/250 source maps are not created in the output directory anymore. This is now done in the context directory. This changes the behavior and also fixes some path problems in source maps on windows.

### CODE REVIEW

**Comment by jhnns** [comment]
Nice! 👍 

Awesome work @cevou

**Comment by philipchmalts** [comment]
Would be awesome to get this merged soon!

File: index.js [hunk 1]
```diff
@@ -35,7 +35,7 @@ function resolveUrlLoader(content, sourceMap) {
   //  however we need to match to the sass-loader and it does not do so
   var loader     = this,
       filePath   = loader.context,
-      outputPath = path.resolve(loader.options.output.path);
+      outputPath = path.resolve(loader.options.context);
```
Comment (bholloway) [inline index.js]: * This variable should be `contextPath`. 
* Per comment below we may need to also keep `outputPath` (proposed second `try`-`catch` block).

File: index.js [hunk 2]
```diff
@@ -57,12 +57,16 @@ function resolveUrlLoader(content, sourceMap) {
...
   if (sourceMap) {
 
     // sass-loader outputs source-map sources relative to output directory so start our search there
     try {
       relativeToAbsolute(sourceMap.sources, outputPath, resolvedRoot);
+      // There are now absolute paths in the source map so we don't need it anymore
+      // However, later when we go back to relative paths, we need to add it again
+      sourceRoot = sourceMap.sourceRoot;
+      sourceMap.sourceRoot = null;
     } catch (exception) {
```
Comment (bholloway) [inline index.js]: Given the number of variants of `sass-loader` that people are using I really want the `resolve-url-loader` to automatically adjust to the source root scheme.

I was thinking a double `try`-`catch` block, one for the new source-root scheme and the second for the old one.

Do you think that it would work?

File: index.js [hunk 3]
```diff
@@ -99,7 +103,10 @@ function resolveUrlLoader(content, sourceMap) {
   if (useMap) {
 
     // source-map sources seem to be relative to the file being processed
-    absoluteToRelative(reworked.map.sources, filePath);
+    absoluteToRelative(reworked.map.sources, path.resolve(filePath, sourceRoot));
```
Comment (bholloway) [inline index.js]: I like terse code but I am not familiar with using `path.resolve` in this particular way.

When `sourceRoot === undefined` (i.e. no source map implies uninitialised) is the result equal to `filePath`?

File: lib/sources-relative-to-absolute.js [hunk 4]
```diff
@@ -44,7 +45,9 @@ module.exports = function sourcesRelativeToAbsolute(sources, defaultBasePath, li
 
       // file was found, now resolve the absolute path
       if (basePath) {
-        array[i] = path.resolve(basePath, location);
+        // rework-css uses urix internally. If we don't convert the path here, the paths are messed up
+        // with the conversion relative urls are set correctly
+        array[i] = urix(path.resolve(basePath, location));
```
Comment (bholloway) [inline lib/sources-relative-to-absolute.js]: I don't have a windows VM right now so I'm relying on your expertise here.

File: index.js (hunk 3 above)
Comment (bholloway) [inline index.js]: Obviously you had a problem with this. Are you able to give me a short explanation on the github issue.

**Comment by bholloway** [comment]
Thanks @cevou for your work on this.

I just started a new job so I'm still installing tools. Give me a day or two and I will be in a better position to help. In the mean time all I can do is make suggestions.

File: index.js (hunk 3 above)
Comment (cevou) [inline index.js]: The paths in the generated source map were not correct. So basically the paths were resolved relative to a wrong directory. 

INCLUDING this change the sources look like this (correct):
```json
{
"sources": [
    "webpack:///../~/open-sans-fontface/sass/_Regular.scss",
    "webpack:///../~/open-sans-fontface/sass/_mixins.scss",
    "webpack:///./components/Test.scss",
    "webpack:///../~/open-sans-fontface/sass/_Bold.scss",
    "webpack:///./styles/styles.scss",
    "webpack:///../~/compass-mixins/lib/compass/css3/_shared.scss",
    "webpack:///./components/sub/Test2.scss"
  ]
}
```

Without the paths are not resolved ocrrectly in the final source map:

```json
{
  "sources": [
    "webpack:///C:/Users/xxx/Software/opensource/~/open-sans-fontface/sass/_Regular.scss",
    "webpack:///C:/Users/xxx/Software/opensource/~/open-sans-fontface/sass/_mixins.scss",
    "webpack:///./components/Test.scss",
    "webpack:///C:/Users/xxx/Software/opensource/~/open-sans-fontface/sass/_Bold.scss",
    "webpack:///../styles/styles.scss",
    "webpack:///./Test.scss",
    "webpack:///C:/Users/xxx/Software/opensource/~/compass-mixins/lib/compass/css3/_shared.scss",
    "webpack:///./components/sub/Test2.scss",
    "webpack:///./components/Test2.scss"
  ]
}
```

File: index.js (hunk 2 above)
Comment (cevou) [inline index.js]: Should we add some tests, so that we can make sure, that we cover most of the different use cases to not mess up someones repo?

File: index.js (hunk 1 above)
Comment (cevou) [inline index.js]: Where does the `contextPath` come from? There is only a `context` property in the webpack config file.
https://webpack.github.io/docs/configuration.html#context

Comment (bholloway) [inline index.js]: Sorry I mean this:
```javascript
   var loader      = this,
       filePath    = loader.context,
       outputPath  = path.resolve(loader.options.output.path);
       contextPath = path.resolve(loader.options.context);
```

Then something like this:
```javascript
    // expect sass-loader@>=4.0.0
    try {
        relativeToAbsolute(sourceMap.sources, contextPath, resolvedRoot);
    }
    // fallback support for sass-loader@<4.0.0
    catch (unused) {
        try {
          relativeToAbsolute(sourceMap.sources, outputPath, resolvedRoot);
        }
        // failed to convert source-map sources
        catch (exception) {
          return handleException('source-map error', exception.message);
        }
    }

    // the asset is specified relative to the sourceRoot, where present
    // sourceRoute is specified relative to the file being processed
    sourceRoot = sourceMap.sourceRoot || undefined;
    sourceMap.sourceRoot = null;
```

File: index.js (hunk 2 above)
Comment (bholloway) [inline index.js]: I agree, but I am not in a position to author right now.

Do you propose an integration test with webpack API?

So far I have a couple of open-source test projects that people have submitted me when they encounter a bug. At minimum I check against them to make sure I don't burn them twice. I will note them here later.

**Comment by bholloway** [comment]
Ok @cevou I created [feature/sass-loader-4](/bholloway/resolve-url-loader/tree/feature/sass-loader-4) which
 * synched latested changes with master (`keepQuery` option)
 * included your PR
 * added support for both versions of `sass-loader`, as proposed

I wanted to keep your commits to credit your contribution. Please let me know if you would be happy with this result.

I have tested with a 'todo' project and it works for `sass-loader@~3.1.x` and `sass-loader@4.0.0`.

Tomorrow I hope to try some of the weird use-cases people have sent me.

**Comment by bholloway** [comment]
FYI. I am about to consider the following historical use cases. As far as I recall both are fixed.

* [sass-rel-paths-issue](/bholloway/sass-rel-paths-issue)
* [webpack-sass-url-issue](/bholloway/webpack-sass-url-issue)

I will need to adjust the `package.json` to use the [feature/sass-loader-4](/bholloway/resolve-url-loader/tree/feature/sass-loader-4) branch. They will still refer to whichever stale/deleted branch solved the issue at the time.

I will check with both `sass-loader@3.2.3` and `sass-loader@4.0.0`.

**Comment by cevou** [comment]
Sounds good to me. Anything I should do before this can be released?

**Comment by bholloway** [comment]
@cevou It seems I am short of use cases.

For your project, if you can use [feature/sass-loader-4](/bholloway/resolve-url-loader/tree/feature/sass-loader-4), and please try both  `sass-loader@3.2.3` and `sass-loader@4.0.0`. I will then be a lot more confident.

**Comment by bholloway** [comment]
Ok. I am happy. @cevou let me know when you are happy.

I was thinking that once you are happy I will merge [feature/sass-loader-4](/bholloway/resolve-url-loader/tree/feature/sass-loader-4) into `pr/23`, so that we can see all the code here. Then I will merge the PR.

I have not done it that way before so any opinions would be valued.

**Comment by cevou** [comment]
I will check my projects when I'm at home later today.

**Comment by cevou** [comment]
I'm happy, too :smile: I also cherry-picked your changes and added them to the pull request.

**Comment by bholloway** [comment]
published as `1.6.0`

**Comment by cevou** [comment]
Thx

**Comment by bholloway** [comment]
No worries @cevou. Thanks for your help.

Sorry I was not around earlier. Thanks @jhnns for fiddling the semver to minimise the impact in the mean time.

**Comment by Klathmon** [comment]
Just wanted to drop in and say thanks to everyone.

This hit me when I upgraded sass loader to 4.0, I found this issue after a bit of searching, followed it and locked my versions, and just upgraded this morning without any issues.

**Comment by jhnns** [comment]
Much appreciated! 👍
